### ISSUE TITLE
Opacity of overlays hides some images.

### ISSUE THREAD

**Issue by mattienodj** [sethkane/textaltcheck#2]
![image](https://user-images.githubusercontent.com/2205238/65393228-c4741500-dd43-11e9-90d3-ecf04032599c.png)
![image](https://user-images.githubusercontent.com/2205238/65393235-d05fd700-dd43-11e9-9edd-ae85eb955263.png)
![image](https://user-images.githubusercontent.com/2205238/65393241-dfdf2000-dd43-11e9-8d5e-3b1c8bcd88e5.png)
I might suggest changed to an rgba color for the background instead of white with opacity. When test driving I noticed that images on the page I was looking at that are already semi-transparent are hidden. Adjusting the CSS helped.

**Comment by sethkane** [comment]
Good one. I will fix this!
