### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by mattienodj** [sethkane/textaltcheck#3]
![image](https://user-images.githubusercontent.com/2205238/65393299-9e9b4000-dd44-11e9-9f0c-e48550032af2.png)
In cases like our silly WP site, where there are bunches of background images, the overlay css ```.textaltcheck a, .textaltcheck div, .textaltcheck span {
    background-image: none !important;
}```

just hides the background. I wonder if there might be an additional warning for large background images as on this page: https://apervita.com/platform/

**Comment by sethkane** [comment]
I am hiding the background images on purpose so you evaluate only the images that require text alternatives.  Does this change your thoughts?  In your sites example, the null value is on the transparent image

![image](https://user-images.githubusercontent.com/2932427/65393534-63e6d700-dd47-11e9-8f2d-c81e69ddd225.png)

Let me know your thoughts?

**Comment by sethkane** [comment]
@mattienodj I checked out your example image example and I am removing them by design but maybe there is a better way to show or highlight background-image elements.  Background images should be considered pure decoration so there should never be any context unless there is another element on the page providing that context.

**Comment by sethkane** [comment]
Notes to self: Research getting the computed background images of every element and if there is one add a pseudo element to put an overlay on top.

var x = document.getElementById("test");
console.log( window.getComputedStyle(x).display )

**Comment by sethkane** [comment]
@mattienodj  Before I create the PR what do you think of this as a solution to your background image concerns?

![image](https://user-images.githubusercontent.com/2932427/65478435-5c125a00-de4f-11e9-951b-281c5f330203.png)

**Comment by sethkane** [comment]
I think #8  should do the trick.  Thanks for the support!

**Comment by mattienodj** [comment]
Neato. I'll keep using it and will share with some peeps.
